#!/usr/bin/env bash
#configure a custom header inside nginx.config

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i '/include \/etc\/nginx\/sites-enabled\/\*;/a \      add_header X-Served-By $hostname;' \
    /etc/nginx/nginx.conf
sudo service nginx start
