#!/usr/bin/env bash
# Install haproxy and configure the load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
#sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "\$ a\listen appname\n\tbind 0.0.0.0:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 68472-web-01 34.207.253.185:80 check\n\tserver 68472-web-02 100.25.135.173:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
