#!/usr/bin/env bash
#configure your nginx to listen to port 80

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i 's/listen\s*80;/listen 0.0.0.0:80;/g' /etc/nginx/sites-available/default
sudo service nginx start
