#!/usr/bin/env bash
# This displays "Best school" 10 times and says "Hi" the 9th time

x=1
while [ $x -le 10 ] 
do
	if [ $x -eq 9 ]
	then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	(( x++ ))
done
