#!/usr/bin/env bash
# This displays "Best school" 10 times but "bad luck" at 4th and "good luck" at 8th

x=1
while [ $x -le 10 ]
do
	if [ $x -eq 4 ]
	then 
		echo "bad luck"
	elif [ $x -eq 8 ]
	then 
		echo "good luck"
	else
		echo "Best School"
	fi
	(( x++ ))
done
