#!/usr/bin/env bash
# This displays 1-20 but "bad luck from China" at 4th and "bad luck from Japan"
# at 7th and "bad luck from Italy" at 17th

x=1
while [ "$x" -le 20 ]
do
	case $x in 
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	*)
		echo "$x"
		;;
	esac
	(( x+=1 ))
done
